title: Open Data for Nonprofit Research
description: This repository is a collection of tools for creating, wrangling, and sharing data and analysis on the nonprofit sector using open data sources
google_analytics: UA-91780879-1
show_downloads: false
theme: jekyll-theme-architect

-gems:
 -  - jekyll-mentions
